### ISSUE TITLE
Requires wifi

### ISSUE THREAD

**Issue by battlesnake** [ktsr42/RsyncServerApp#4]
On my old phone, I'd start Rsync via `adb shell`, then use `adb forward` and rsync between PC/phone over USB.

I can't run binaries from `adb shell` on my new phone, so I tried this app.

Currently, it appears that it requires a wifi connection.

I actually have an rsync config file already on my phone (configured for `127.0.0.1:6000` or similar) - would it be possible for the app to have an option to allow starting the server on `localhost`, or otherwise an option to select and pass a file as `--config` argument to the rsync binary?

Thanks!

I'm cloning the repo now, if it looks easy enough for me (not familiar with android dev) then I'll send you a PR soon.

**Comment by ktsr42** [comment]
Hi. So the requirement for the wifi network being present is only here for security purposes. Originally I also planned to create the server socket restricted to that network/interface as well but it turned out that Android has a bug that prevents this from working.

Long story short, we can probably have a checkbox in the gui that waives the requirement that wifi is available. That should get you where you want to go if I understood you correctly.

It may take me a while to make this happen though as I am quite busy at the moment.

BTW, I am running [Lineage OS](http://lineageos.org) on my phone - I am actually buying new phones only after studying their [HW compatibility list](https://wiki.lineageos.org/devices/). The trick is to stay away from phones that require rooting the existing OS.

**Comment by battlesnake** [comment]
I used to use LineageOS on my old phone, but I want to wait until I've had this one a year before modding it, in case I need to call on the warranty.

I got my transferworking in the end by writing a script that copies a static rsync binary to `/data/local/tmp` (no noexec there), and starts it from there with my custom config file, then sets up the ADB port forwarding.
