### ISSUE TITLE
Transfer fails with: java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by capocasa** [ktsr42/RsyncServerApp#6]
Getting an error message after starting rsync from client:

    $ rsync -av rsync://192.168.1.123:12345/123456/DCIM/ ./Camera-Backup
    receiving incremental file list
    Failed to read directory /storage/emulated/0/DCIM/.: java.nio.file.AccessDeniedException: /storage/emulated/0/DCIM/.

A quick google search pointed me to this [stack overflow answer](https://stackoverflow.com/a/64629155/187273) which may be relevant:

_For android 10 and 11 add this line to your <application> element in the android manifest file. hope it will work:_

    <application
      android:requestLegacyExternalStorage="true"

**Comment by ktsr42** [comment]
The app explicitly requests permission to access files in "shared storage". I am guessing that you confirmed that?

**Comment by qwerty-in-me** [comment]
I can assure you, the manifest change is needed for the aformentioned versions, because AOSP likes to make things difficult, complicated and obtuse. 

I used the original version downloaded from F-Droid, t'was up to date and I got the same error as capocasa did. Then I changed the manifest and rsync could propperly access storage, I couldn't test if it works as the only network connection between my phone and PC is RNDIS ( Android is very restrictive and thus the connection was refused )

**Comment by ktsr42** [comment]
This should now be fixed in the latest revision. The underlying cause was that with Android 10, the permissions for accessing the shared files changed (https://developer.android.com/about/versions/10/privacy/changes#scoped-storage) as well as the mechanisms for requesting it.

I made the necessary code changes to support both legacy and Android 10 and above (https://github.com/ktsr42/RsyncServerApp/blob/b4a6a3648e80d6ab7c69665dbc0b41efd46b50d4/app/src/main/java/com/github/ktsr42/rsyncserver/MainActivity.java#L193).

Theoretically FDroid should pick the new release (release tag) up automatically. However, this is my first app ever (my day job is in a totally different field) so chances are that it will not work and FDroid does not pick up the new release by itself. I am monitoring for that and will close this thread once my phone receives it.

If anybody needs the upgrade urgently and can enable developer mode on the phone (https://www.lifewire.com/how-to-enable-developer-mode-on-android-4684044), you can try building it yourself. It involves installing Android Studio, cloning this repo locally, building the app in Studio and pushing it to the phone from there.

**Comment by ktsr42** [comment]
Ok, the update is finally in Fdroid.
